services:
  - type: web
    name: styleme-strapi
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337

      # 🔐 Secrets
      - key: APP_KEYS
        value: tGTFfGXs1/cv3GPnVmXNRA==,uxNiBtDp6H/GpdgLJaXRCQ==,iZckkhVZmV5O6N2DvFrZDw==,9mm2IFxE4CINRlNjCmFxqQ==
      - key: API_TOKEN_SALT
        value: stRVlrPQaSg6Wpk5eTPf0w==
      - key: ADMIN_JWT_SECRET
        value: XHEwIRAn7irmUNGZmtA54g==
      - key: TRANSFER_TOKEN_SALT
        value: yq8ROgU+HGcMRUhItEt2tw==
      - key: JWT_SECRET
        value: Pv2GFJDxY1anytKHtNG+mw==

      # 🛢 Database
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_iHwU2FjS4cMK@ep-quiet-darkness-a477kfpp-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: DATABASE_HOST
        value: ep-quiet-darkness-a477kfpp-pooler.us-east-1.aws.neon.tech
      - key: DATABASE_PORT
        value: 5432
      - key: DATABASE_NAME
        value: neondb
      - key: DATABASE_USERNAME
        value: neondb_owner
      - key: DATABASE_PASSWORD
        value: npg_iHwU2FjS4cMK
      - key: DATABASE_SSL
        value: "true"
