services:
  - type: web
    name: styleme-strapi
    env: node
    repo: https://github.com/yourusername/styleme-strapi
    buildCommand: yarn build
    startCommand: yarn start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
      - key: RENDER_EXTERNAL_URL
        value: https://styleme-strapi.onrender.com

      # Database (Neon)
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        sync: false

      # Secrets (you must add them manually in Render dashboard)
      - key: APP_KEYS
        sync: false
      - key: API_TOKEN_SALT
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: TRANSFER_TOKEN_SALT
        sync: false
      - key: JWT_SECRET
        sync: false
